<?php

use App\Http\Controllers\AppConfigController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\CreditCardController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\RecipesController;
use App\Http\Controllers\ExpensesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvestmentsController;
use App\Http\Controllers\InvoicesController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/',                                    [HomeController::class, 'index'])->name('home');
Route::get('/register',                            [HomeController::class, 'register'])->name('register');
Route::post('/register/new',                       [HomeController::class, 'newUser']);
Route::post('/login',                              [AuthController::class, 'login'])->name('login');
Route::get('/logout',                              [AuthController::class, 'logout'])->name('logout');
Route::get('/session',                             [AuthController::class, 'session']);
Route::middleware(['is.authenticated'])->group(function() {
    Route::get('/dashboard',                        [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/config',                           [DashboardController::class, 'config'])->name('config');
    Route::post('/first-access',                    [DashboardController::class, 'firstAccess'])->name('first-access');
    Route::get('/initial',                          [DashboardController::class, 'initial'])->name('initial');
    Route::get('/app/url',                          [DashboardController::class, 'appUrl']);
    Route::get('/categories',                       [CategorieController::class, 'index'])->name('categories.index');
    Route::get('/categories/{id}',                  [CategorieController::class, 'show']);
    Route::post('/categories/store',                [CategorieController::class, 'store']);
    Route::post('/categories/update',               [CategorieController::class, 'update']);
    Route::get('/categories/destroy/{id}',          [CategorieController::class, 'destroy']);
    Route::get('/cards',                            [CreditCardController::class, 'index'])->name('cards.index');
    Route::post('/cards/store',                     [CreditCardController::class, 'store']);
    Route::get('/cards/{id}',                       [CreditCardController::class, 'show']);
    Route::post('/cards/update',                    [CreditCardController::class, 'update']);
    Route::get('/cards/destroy/{id}',               [CreditCardController::class, 'destroy']);
    Route::get('/cards/switch-status/{id}',         [CreditCardController::class, 'switchStatus']);
    Route::get('/users',                            [UserController::class, 'index'])->name('users.index');
    Route::get('/users/password/generate',          [UserController::class, 'passwordGenerate']);
    Route::get('/users/{id}',                       [UserController::class, 'show']);
    Route::post('/users/store',                     [UserController::class, 'store']);
    Route::post('/users/update',                    [UserController::class, 'update']);
    Route::get('/recipes',                          [RecipesController::class, 'index']);
    Route::get('/recipes/{id}',                     [RecipesController::class, 'show']);
    Route::post('/recipes/store',                   [RecipesController::class, 'store']);
    Route::post('/recipes/update',                  [RecipesController::class, 'update']);
    Route::get('/recipes/destroy/{id}',             [RecipesController::class, 'destroy'])->name('recipe.destroy');
    Route::get('/expenses',                         [ExpensesController::class, 'index']);
    Route::get('/expenses/{id}',                    [ExpensesController::class, 'show']);
    Route::get('/expenses/destroy/{id}',            [ExpensesController::class, 'destroy']);
    Route::get('/expenses/destroy/all/{id}',        [ExpensesController::class, 'destroyAll']);
    Route::post('/expenses/store',                  [ExpensesController::class, 'store']);
    Route::post('/expenses/update',                 [ExpensesController::class, 'update']);
    Route::post('/expenses/revert/{id}',            [ExpensesController::class, 'revert']);
    Route::post('/expenses/verify/payment',         [ExpensesController::class, 'verifyMetodPayment']);
    Route::post('/expenses/cancel/one',             [ExpensesController::class, 'cancelOneInstallment']);
    Route::post('/expenses/cancel/all',             [ExpensesController::class, 'cancelAllInstallments']);
    Route::post('/expenses/extend/{id}',            [ExpensesController::class, 'extendInstallments']);
    Route::post('/expenses/history/{id}',           [ExpensesController::class, 'history']);
    Route::post('/expenses/pay/{id}',               [ExpensesController::class, 'pay']);
    Route::get('/reports/expenses-by-category',     [ReportController::class, 'expensesByCategory'])->name('report.expenses.category');
    Route::get('/reports/recipes-all',              [ReportController::class, 'allRecipes'])->name('report.recipes.all');
    Route::post('/reports/search',                  [ReportController::class, 'search']);
    Route::get('/investments',                      [InvestmentsController::class, 'index'])->name('investments.index');
    Route::get('/billing',                          [BillingController::class, 'index'])->name('billing.index');
    Route::get('/billing/{id}',                     [BillingController::class, 'show']);
    Route::get('/billing/destroy/{id}',             [BillingController::class, 'destroy']);
    Route::get('/billing/convert/{id}',             [BillingController::class, 'convert']);
    Route::post('/billing/store',                   [BillingController::class, 'store']);
    Route::post('/billing/update',                  [BillingController::class, 'update']);
    Route::post('/billing/refuse',                  [BillingController::class, 'refuse']);
    Route::get('/tickets',                          [TicketController::class, 'index'])->name('tickets');
    Route::post('/invoices/pay',                    [InvoicesController::class, 'pay']);
    Route::post('/config/store',                    [AppConfigController::class, 'store']);
    Route::get('/charts/index',                     [ChartController::class, 'index']);
    Route::get('/notifications',                    [NotificationController::class, 'index'])->name('notifications.index');
    Route::get('/notifications/get',                [NotificationController::class, 'get']);
    Route::get('/notifications/read',               [NotificationController::class, 'read']);
});
